version: '3.1'

services:

  campusdb:
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-network

  campuspma:
    depends_on:
      - campusdb
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8084:80
    env_file: .env
    environment:
      PMA_HOST: campusdb
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - spring-network

  campuscms:
    depends_on:
      - campusdb
      - campuspma
    restart: unless-stopped
    image: "ghcr.io/queerzard/campusonspring:latest"
    ports:
      - 8804:8080
    env_file: .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      SPRING_DATASOURCE: 'jdbc:mariadb://campusdb:3306/${MYSQL_DATABASE}?autoReconnect=true&useSSL=false'
    networks:
      - spring-network

volumes:
  db-data:

networks:
  spring-network:
    driver: bridge