name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Push the Docker image
        run: |
          docker login --username queerzard --password ${{ secrets.gh_pat }} ghcr.io 
          docker build . --tag ghcr.io/queerzard/campusonspring:latest 
          docker push ghcr.io/queerzard/campusonspring:latest 
          
